### ISSUE TITLE
Could not find de.richsource.gradle.plugins:gwt-gradle-plugin:1.0.6.

### ISSUE THREAD

**Issue by zjc121** [libgdx/libgdx-demo-pax-britannica#15]
Could not find de.richsource.gradle.plugins:gwt-gradle-plugin:1.0.6.
Searched in the following locations:
    https://jcenter.bintray.com/de/richsource/gradle/plugins/gwt-gradle-plugin/1.0.6/gwt-gradle-plugin-1.0.6.pom
    https://jcenter.bintray.com/de/richsource/gradle/plugins/gwt-gradle-plugin/1.0.6/gwt-gradle-plugin-1.0.6.jar
    https://repo1.maven.org/maven2/de/richsource/gradle/plugins/gwt-gradle-plugin/1.0.6/gwt-gradle-plugin-1.0.6.pom
    https://repo1.maven.org/maven2/de/richsource/gradle/plugins/gwt-gradle-plugin/1.0.6/gwt-gradle-plugin-1.0.6.jar
    https://oss.sonatype.org/content/repositories/snapshots/de/richsource/gradle/plugins/gwt-gradle-plugin/1.0.6/gwt-gradle-plugin-1.0.6.pom
    https://oss.sonatype.org/content/repositories/snapshots/de/richsource/gradle/plugins/gwt-gradle-plugin/1.0.6/gwt-gradle-plugin-1.0.6.jar
Required by:
    :libgdx-demo-pax-britannica-master:unspecified

**Comment by MrStahlfelge** [comment]
@MobiDevelop @Tom-Ski Can you update the dependencies for the project? New users have a problem and don't know the correct ones to fix this locally.

**Comment by maikotrindade** [comment]
The same issue in other demos, this jeopardize the learning of this technology

**Comment by rpahut** [comment]
Newly generated projects do reference org.wisepersist:gwt-gradle-plugin: , this seem to be the correct dependency.
@Tom-Ski might be qualified to make a call here.

**Comment by tommyettinger** [comment]
This project now references the same Gradle plugins that a current gdx-setup project does, though a newer version for each. That should mean this is resolved.

**Comment by UjuiUjuMandan** [comment]
> de.richsource.gradle.plugins:gwt-gradle-plugin:1.0.6. 仓库地址更改了： org.wisepersist:gwt-gradle-plugin:

> "Repo address changed"

No, this is a fork of de.richsource,

> It was originally [created by Steffen Schaefer](https://github.com/steffenschaefer/gwt-gradle-plugin). Really appreciate his effort on making this great plugin.
>
> In last two years, there were no updates in the original git repo, so we plan to continue the maintenance in this fork.
> https://github.com/jiakuan/gwt-gradle-plugin/tree/v1
