### ISSUE TITLE
javax.net.ssl.SSLHandshakeException error occured when making a desktop build

### ISSUE THREAD

**Issue by nykevinwong** [libgdx/libgdx-demo-pax-britannica#17]
C:\temp\libgdx-demo-pax-britannica>gradlew -version --info
Initialized native services in: C:\Users\kevin\.gradle\native

------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.7.0_55 (Oracle Corporation 24.55-b03)
OS:           Windows 8.1 6.3 x86

C:\temp\libgdx-demo-pax-britannica>gradlew desktop:run
Parallel execution with configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\temp\libgdx-demo-pax-britannica\build.gradle' line: 5

* What went wrong:
A problem occurred evaluating root project 'libgdx-demo-pax-britannica'.
> javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s

C:\temp\libgdx-demo-pax-britannica>

**Comment by tommyettinger** [comment]
This is most likely a Java 7 issue, since some of Java's networking technology was outdated and dropped from widescale usage after some early Java 8 releases (for security reasons). Java 7 is EOL now, and isn't able to build LWJGL3 projects, so I'll close this.
